version: "3.9"
services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: limits-service:1.0
    network_mode: "host" # Use host network
    stdin_open: true
    tty: true